### ISSUE TITLE
Need to run as root

### ISSUE THREAD

**Issue by cbhushan051** [surya-veer/movement-tracking#1]
I can't run the program without root or with root. and it need to be rooted to aggregate the keyboard(kbd).

**Comment by surya-veer** [comment]
using linux or windows?

**Comment by GuancongLuo** [comment]
@cbhushan051  I have the same problems using Ubunto20.04. How to solve it?

**Comment by surya-veer** [comment]
quick solution, 
Import pyautogui
and replace keyboard.press_and_release to pyautogui.hostkey

hope it will work.

**Comment by GuancongLuo** [comment]
Yes, It is work!

**Comment by cbhushan051** [comment]
> using linux or windows?

Sorry for late reply...But above solution works well..thanks.
