### ISSUE TITLE
msmf: init stream failed to set mediaType

### ISSUE THREAD

**Issue by Abhinaygunjal** [surya-veer/movement-tracking#13]
I am new to opencv and i found your project of great interest. Please rectify this error that has been raised in the 'assertion failed' code that you uploaded.

**Comment by surya-veer** [comment]
Hey not releted to code.this is releted to your hardware.
Check open issue you will find it. 
Please read issue before create new one.

**Comment by Abhinaygunjal** [comment]
Okay, Thank you very much!
