### ISSUE TITLE
Getting a runtime Error

### ISSUE THREAD

**Issue by harjotscs** [surya-veer/movement-tracking#3]
When I run the code it throws this error

Traceback (most recent call last):
  File "E:/ml/movement-tracking/movement-v2.py", line 83, in <module>
    img, nose_cords = detect_nose(img, faceCascade)
  File "E:/ml/movement-tracking/movement-v2.py", line 11, in detect_nose
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

Please help

**Comment by harjotscs** [comment]
Going to close this issue as I got it's fix just need to change **video_capture = cv2.VideoCapture(-1)** on line 67 to **video_capture = cv2.VideoCapture(0)** in movement-v2.py

**Comment by surya-veer** [comment]
Thanks!
