### ISSUE TITLE
It's not detecting the up and left manner of motion 

### ISSUE THREAD

**Issue by Devansh2005** [surya-veer/movement-tracking#5]

**Comment by surya-veer** [comment]
@Devansh2005 If you are talking about v2 then you need to train your self :P a bit. I have simply added displacement and velocity to check movement. Probably next weekend I will try to add recurrent logic to track movements. Which will make things smooth.

**Comment by shruthi-22** [comment]
Can you say why is left and down not working properly so i could try it out

**Comment by surya-veer** [comment]
@shruthi-22, I have simply added displacement and velocity to check movement. Probably next weekend I will try to add recurrent logic to track movements. Which will make things smooth.
**A solution that you can try:** Try to memorize the motion and calculate displacement vector in given time lets say 300ms. And decide whether left-right-top-down.
Hope it will work, 
If you are able to do this then raise a merge request. I will be more than happy to approve it.
