### ISSUE TITLE
 (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

### ISSUE THREAD

**Issue by SouroMLhub** [surya-veer/movement-tracking#6]
Assertion failed in line number 11.

Showing error- error: OpenCV(4.3.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by surya-veer** [comment]
@SouroMLhub Please read the readme or check this older issue:(https://github.com/surya-veer/movement-tracking/issues/4)
